import {createAction} from 'redux-actions'

export const PRODUCTS_DESCRIPTION_REQUEST = createAction('PRODUCTS_DESCRIPTION_REQUEST');
export const PRODUCTS_DESCRIPTION_SUCCESS = createAction('PRODUCTS_DESCRIPTION_SUCCESS');
export const PRODUCTS_DESCRIPTION_FAILURE = createAction('PRODUCTS_DESCRIPTION_FAILURE');
