import {createAction} from 'redux-actions'

export const REMOVE_PRODUCT_FROM_CART = createAction('REMOVE_PRODUCT_FROM_CART');
export const REMOVE_PRODUCT_FROM_CART_REQUEST = createAction('REMOVE_PRODUCT_FROM_CART_REQUEST');
export const REMOVE_PRODUCT_FROM_CART_SUCCESS = createAction('REMOVE_PRODUCT_IN_CART_SUCCESS');
export const REMOVE_PRODUCT_FROM_CART_FAILURE = createAction('REMOVE_PRODUCT_IN_CART_FAILURE');
